- name: Install application
  gather_facts: no
  hosts: wordpress
  become: true

  tasks:
  - name: Creates /opt/app directory
    file:
      path: /opt/app
      state: directory
      owner: centos
      group: centos
      mode: 0775
      recurse: yes

  - name: create docker-compose file
    become: yes
    template:
      src: templates/docker-compose.yml.j2
      dest: /opt/app/docker-compose.yml
      owner: centos
      group: centos
      mode: 0775

  - name: create Caddyfile file
    become: yes
    template:
      src: templates/Caddyfile
      dest: /opt/app/Caddyfile
      owner: centos
      group: centos
      mode: 0775

  - name: create motd file
    become: yes
    template:
      src: templates/motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
    tags:
      - motd
